### ISSUE TITLE
Issue with the Storage Provider Rest HTTP requests

### ISSUE THREAD

**Issue by alplabin** [bnb-chain/greenfield-docs#26]
As explained in the document shared on the telegram conversation, multiple http request presented in the [Storage Provider Rest](https://greenfield.bnbchain.org/docs/api-sdk/endpoints.html) are not following the rules. Some changes should be made:

- [Get Approval](https://greenfield.bnbchain.org/docs/api-sdk/storgae-provider-rest/get_approval.html) (**GET** -> **POST**) - Since a new approval and ID is created with each request, it's recommended to use the POST method for this operation;
- [Challenge Object Data](https://greenfield.bnbchain.org/docs/api-sdk/storgae-provider-rest/challenge.html) (**GET** -> **POST**) – Likewise, using a GET request to create a new challenge is not feasible. In this case, a POST request should be used instead;
- [Put Object](https://greenfield.bnbchain.org/docs/api-sdk/storgae-provider-rest/put_object.html) (**PUT** -> **POST**) -  If the ETag is calculated using data other than just the object name (e.g: the date), then the response body of the HTTP request will never  be the same if you upload the same document. In this scenario, since the  HTTP request is not idempotent, you'll need to update the request to use the POST method instead;
- [Replicate Object Data](https://greenfield.bnbchain.org/docs/api-sdk/storgae-provider-rest/replicate_object_data.html) (**PUT** -> **POST**) – Similarly to the previous page, if the ID, Integrity-Hash, or  Hash-Signature values returned from the server differ when sending the same data, a POST request should be used instead of a PUT request.

**Comment by sysvm** [comment]
@alplabin Thanks for your questions.
- [Get Approval](https://greenfield.bnbchain.org/docs/api-sdk/storgae-provider-rest/get_approval.html) We use `GET` instead of `POST` because SP just sign user's message and it doesn't change the server status of SP. This is an idempotent API.
- [Challenge Object Data](https://greenfield.bnbchain.org/docs/api-sdk/storgae-provider-rest/challenge.html) This API is used to challenge user's object and it doesn't change the server status of SP. This is an idempotent API.
- [Put Object] We use `PUT` method to upload an object for compatible with AWS S3. Currently there are no very complex scenarios that require `POST`. If any, we'll add `POST` in the future.
- [Replicate Object Data](https://greenfield.bnbchain.org/docs/api-sdk/storgae-provider-rest/replicate_object_data.html)This API is idempotent. You put an object once and you put it many times and the result is the same.

**Comment by alplabin** [comment]
I see, thank you for clarifying that.

However, I still believe that the `Get Approval` and `Challenge Object Data` methods should not be GET request since it is used for signing or challenging information and a GET request is only used for retrieving information, not for modifying it.

Additionally, could you please confirm whether the `Put Object` method is also idempotent?

**Comment by sysvm** [comment]
OK, I see.
- `Get Approval` API returns ID is request id which is used to trace api request for troubleshooting online problems. You can refer AWS S3 will return version id in header https://docs.aws.amazon.com/zh_cn/AmazonS3/latest/API/API_PutObject.html.
- `Challenge Object Data` API is an inner API which shouldn't be exposed to external user. I'll delete this API in docs. And I'll provide a new API named `GetChallengeInfo` which is a `GET` method for retrieving information.
- `Put Object` is idempotent. Because if a user upload an object multi times, `Put Object` will return the same ID.
- `Replicate Object Data` is an inner API which shouldn't be exposed to external user.  I'll delete this API in docs.

**Comment by alplabin** [comment]
@sysvm Thanks again for the explanation. 

I still have a question about the `Get Approval` API. I'm not sure if I understood everything correctly from your explanation.
Is the `X-Gnfd-Request-ID` returned by the API similar to the `version ID` used in AWS PutObject? If so, does that mean the API is used to get the `version ID` of the Bucket? 
If that's the case, maybe it may be helpful to change the name of the API to `Get Bucket ID`.

I was also wondering if the `X-Gnfd-Unsigned-Msg` that is sent is similar to the `X-Gnfd-Signed-Msg` that's returned. Does that mean the message changes status from `Unsigned` to `Signed`?

**Comment by sysvm** [comment]
@alplabin You misunderstood my description. I use version id in AWS S3 is to explain `X-Gnfd-Request-ID` is always variational. This field should not be used as a basis for using `POST` and it's not bucket id.
`Get Approval` uses sign algorithm to sign `X-Gnfd-Unsigned-Msg`. So as you said, the message changes status form `Unsigned` to `Signed`.
I pull a request to delete `Challenge Object Data` API. This API isn't inappropriate now. I'll write a new API which called `GetChallengeInfo`.

**Comment by alplabin** [comment]
@sysvm Thanks again for giving more explanations.

So, if I understand correctly, the `Get Approval` API is only used to retrieve an existing ID and nothing more. 
Or, as you said, the message `X-Gnfd-Unsigned-Msg` is transformed to a signed message using the `Get Approval` API? In that case, it wouldn't be possible to accomplish this with a `GET` request. Instead, it would require a `PUT` or `POST` request, depending on whether the result of all header parameters are idempotent.

**Comment by sysvm** [comment]
The id returned by `Get Approval` is not important, because users doesn't need to care about ID. This id is used to trace request in distributed tracing system.

About `X-Gnfd-Unsigned-Msg`, the status of sp server is not changed. I understand your thoughts, so I think this point should be discussed whether to use `POST` or `PUT`.

**Comment by alplabin** [comment]
If the message change from `unsigned` to `signed`, something should be changed either in the server or the database? If you've already changed a message from `unsigned` to `signed` and you try to resend it, I think that you should receive a new `ID`. In that case, you should use a `POST` request.

**Comment by sysvm** [comment]
There is nothing changed in the server or database when a message changes from `unsigned` to `signed`. I just use a sign method and don't record any information. The ID returned has no association with the signature information.

**Comment by alplabin** [comment]
How can you determine if a previously signed message has already been signed if the user resends the same message?

**Comment by sysvm** [comment]
SP would check the signed message that the field of signature exists a value without using database.

**Comment by alplabin** [comment]
When a message is signed, it gets added to the signature field? If so, even though it isn't the server or the database, something is changing.

In case of a resent signed message, what kind of message will the API return?"

**Comment by sysvm** [comment]
About `In case of a resent signed message, what kind of message will the API return?`, the same message will be returned.

**Comment by alplabin** [comment]
Why would the message be the same if the message is already signed?

**Comment by sysvm** [comment]
@alplabin Thanks, the design of `Get Approval` is not reasonable and this is important. I'll make a new design.

**Comment by alplabin** [comment]
Thanks! Let me know if I can help you.

**Comment by sysvm** [comment]
You're welcome. If I finish that, I'll make a pr to notify you. I'll close this issue.
